### ISSUE TITLE
How to handle attributes such as `target="_blank"`?

### ISSUE THREAD

**Issue by JESii** [nocd5/md2html#16]
Love the Table of Contents which you create and I really want to use this program.

However, I can't figure out how to add an attribute to the URL -- I don't want a link to replace the current page; I want it to open in a new tab.

Do you have a way to specify that? When using Pandoc, I just appended `{target=\\"\_blank\\"}` following the ")" at the end of the URL definition.

Hopefully something I'm missing as I really love the output of this program.

**Comment by nocd5** [comment]
Unfortunately, this app has no command-line option or syntax for appending `target="_blank"` to the `<a>` tag.
However your issue is motivating for adding the new feature, thank you.

There is a workaround.
insert a line `<div><base target="_blank"></div>` to somewhere (header or footer etc.) in the markdown file.
All links will be opened in new tab.

**Comment by JESii** [comment]
Thanks; ~~tried that but no matter where I put that line, it winds up wrapped in a `<style>` block and doesn't work~~. My error; definitely working now!
